# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chris Bishop - Software Engineer
author:
  email: cjbishop1986@gmail.com
  name: Chris Bishop
description: >- # this means to ignore newlines until "baseurl:"
  My name is Chris Bishop. I am a Cloud Software Engineer with 14+ years of success transforming challenging business initiatives into innovative, yet sustaining, technology solutions. I have a demonstrated history of expertise leveraging emerging technology to manage multiple production workloads as a key member of the Core Engineering Team for an industry leading SaaS, Data, and Analytics provider.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Remote the Theme to get latest version from Github:
remote_theme: jekyll/minima

# Global Permalink URL format for Pages and Posts (Can be overriden at collection level if desired)
# See: https://jekyllrb.com/docs/permalinks/
# Result: /:categories/:year/:month/:day/:title/
permalink: pretty

# Pages to link in Header
header_pages:
  - index.markdown
  - about.markdown
  - resume.markdown
  - certifications.markdown
  - contact.markdown

# CJB Custom - Assume the Role Logo Images
atr_logo_notxt: /assets/logo-img-notext-color-stroked.png
atr_logo_noimg: /assets/logo-text-noimg-color-stroked.png
atr_logo_imgtxt: /assets/logo-img-text-color-stroked.png

# CJB Custom - Show Snippets from Recent Posts on Home page, Social Media Shares, Google Search Results
# TODO - Need to find where this can be configured with regard to image size and amount of content (Lines) in addition to styles. Commenting for now as it currently shows TOO MUCH!
#show_excerpts: true

# Theme Skin
minima:
  skin: dark
  # Social Networks
  social_links:
    linkedin: chris-bishop-084b26a
    twitter: ChrisBi73512691
    github: chris-bishop
    stackoverflow: "13297682"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
